server:
  contextPath: /
  port: 9090
spring:
  profiles:
    active: dev
  application:
    name: spring-activiti
    #排除文件 报Could not find class [org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration]
    #autoconfigure:
      #exclude:
    #  - org.activiti.spring.boot.SecurityAutoConfiguration
---
spring:
  profiles: dev
  #activiti工作流相关
  activiti:
    check-process-definitions: true #自动检查、部署流程定义文件
    database-schema-update: true #自动更新数据库结构
    #流程定义文件存放目录
    process-definition-location-prefix: classpath:/processes/
  datasource:
    url: jdbc:mysql://47.94.226.83:3306/yxsd?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: Sc123456@
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-monitor:
        enabled: true
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 30000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxEvictableIdleTimeMillis: 2000000
    #validationQuery: SELECT 1
    validationQuery: SELECT 1 FROM DUAL
    validationQueryTimeout: 10000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shan.entity


